# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
xcode_project: TableauExample.xcodeproj
xcode_scheme: TableauExampleTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X